### ISSUE TITLE
Missing TLS Path from config

### ISSUE THREAD

**Issue by Dawn-Piper** [IoDLT/catapult-devnet#2]
When running the startup script

error:
```
cat-rest-api | error: rest server is exiting due to errorpath must be a string or Buffer {"stack":"TypeError: path must be a string or Buffer\n    at Object.fs.openSync (fs.js:646:18)\n    at Object.fs.readFileSync (fs.js:551:33)\n    at connectToDbWithRetry.then (/usr/src/app/rest/rest/_build/index.js:177:21)\n    at <anonymous>\n    at process._tickCallback (internal/process/next_tick.js:189:7)","timestamp":"2020-05-29T18:09:17.553Z"}
```
which is caused by:
```
rest/rest.json
```
not having the TLS certificate paths set as per https://github.com/nemtech/catapult-rest
(the code for the rest api)

As per lines 175 to 183 of https://github.com/nemtech/catapult-rest/blob/master/rest/src/index.js

The configuration has been removed from the rest.json but appears to be required.

**Comment by Dawn-Piper** [comment]
Seems that these params were added in commit [7d242f4247fa1ebe281a1f38d484cb00b64f823e](https://github.com/nemtech/catapult-rest/commit/7d242f4247fa1ebe281a1f38d484cb00b64f823e#diff-84017da833911d1711fec377da4f997c) in the main repo

**Comment by CrackTheCode016** [comment]
Hi @Dawn-Piper, thanks so much for raising this issue.  I'm currently in the process of getting everything setup and working with the TLS, VRF updates + .  It should be done by Monday.  Thank you again for bring this to my attention!

**Comment by CrackTheCode016** [comment]
TLS has been integrated into the `v0.9.5.1` branch, and will be merged soon into master.
